/** @type {import('tailwindcss').Config} */
export default {
	content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
	darkMode: "class",
	theme: {
		extend: {
			letterSpacing: {
				wide: "0.04em",
				tighter: "0.01em",
				normal: "0.03em",
			},
			lineHeight: {
				normal: "1.5",
				wide: "1.8",
				tighter: "1.2",
			},
			colors: {
				accent: {
					light: "var(--accent-light)",
					dark: "var(--accent-dark)",
				},
			},
		},
	},
	variants: {
		extend: {
			opacity: ["hover"],
			scale: ["hover"],
			textColor: ["dark", "hover"],
			backgroundColor: ["dark", "hover"],
			borderColor: ["dark"],
		},
	},
	corePlugins: {
		preflight: false,
		backdropBlur: false,
		backdropBrightness: false,
		backdropContrast: false,
		backdropFilter: false,
		backdropGrayscale: false,
		backdropHueRotate: false,
		backdropInvert: false,
		backdropOpacity: false,
		backdropSaturate: false,
		backdropSepia: false,
		backgroundAttachment: false,
		backgroundBlendMode: false,
		backgroundClip: false,
		backgroundImage: false,
		backgroundOrigin: false,
		backgroundPosition: false,
		backgroundRepeat: false,
		backgroundSize: false,
		blur: false,
		borderCollapse: false,
		borderSpacing: false,
		borderStyle: false,
		boxDecorationBreak: false,
		// boxShadow: false,
		boxSizing: false,
		breakAfter: false,
		breakBefore: false,
		breakInside: false,
		brightness: false,
		caretColor: false,
		clear: false,
		columns: false,
		container: false,
		contrast: false,
		cursor: false,
		divideColor: false,
		divideOpacity: false,
		divideStyle: false,
		divideWidth: false,
		dropShadow: false,
		fill: false,
		filter: false,
		float: false,
		fontFamily: false,
		fontSmoothing: false,
		fontStyle: false,
		fontVariantNumeric: false,
		// gap: false,
		gradientColorStops: false,
		grayscale: false,
		gridAutoColumns: false,
		gridAutoFlow: false,
		gridAutoRows: false,
		gridColumn: false,
		gridColumnEnd: false,
		gridColumnStart: false,
		gridRow: false,
		gridRowEnd: false,
		gridRowStart: false,
		gridTemplateColumns: false,
		gridTemplateRows: false,
		hueRotate: false,
		invert: false,
		isolation: false,
		justifyItems: false,
		justifySelf: false,
		listStyleImage: false,
		listStylePosition: false,
		listStyleType: false,
		maxHeight: false,
		mixBlendMode: false,
		objectFit: false,
		objectPosition: false,
		order: false,

		overflow: false,
		overscrollBehavior: false,
		placeContent: false,
		placeItems: false,
		placeSelf: false,
		placeholderColor: false,
		placeholderOpacity: false,
		pointerEvents: false,
		resize: false,

		rotate: false,
		saturate: false,
		scrollBehavior: false,
		scrollMargin: false,
		scrollPadding: false,
		scrollSnapAlign: false,
		scrollSnapStop: false,
		scrollSnapType: false,
		sepia: false,
		skew: false,
		stroke: false,
		strokeWidth: false,
		tableLayout: false,
		textDecoration: false,
		textDecorationColor: false,
		textDecorationStyle: false,
		textDecorationThickness: false,
		textIndent: false,
		textOpacity: false,
		textOverflow: false,
		textTransform: false,
		textUnderlineOffset: false,
		touchAction: false,
		transformOrigin: false,
		translate: false,
		userSelect: false,
		verticalAlign: false,
		visibility: false,
		whitespace: false,
		willChange: false,
		wordBreak: false,
	},
};
